/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 mac-draco.gltf --transform 
Files: mac-draco.gltf [522.08KB] > mac-draco-transformed.glb [50.05KB] (90%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/mac-draco-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.screen.geometry} material={materials['screen.001']} position={[0.002, 2.928, 0.327]} rotation={[1.585, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/mac-draco-transformed.glb')
